name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  validate-branch:
    name: Ensure PR to main comes from release/*
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get last commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"
          if ! echo "$COMMIT_MESSAGE" | grep -E "Merge pull request #.* from .*release/"; then
            echo "🚫 Push para main só pode vir de release/*"
            exit 1
          fi

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: validate-branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create .env file with secrets
        run: |
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> .env
          echo "REACT_APP_CLIENT_SECRET=${{ secrets.REACT_APP_CLIENT_SECRET }}" >> .env
          echo "REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
